#! /bin/bash
#set -euxo pipefail

config="/etc/shadowsocks.json"
configbk="/etc/shadowsocks.json.bk"

if [ $# -ne 2 ]
then
    echo "[INFO] Current config:"
    cat $config
    echo "[ERROR] Usage: ssport oldPort newPort"
    echo "               ssport newPort Password"
    exit 1
fi

oldPort=$1
newPort=$2

echo "[INFO] try to change $oldPort to $newPort"


cp $config $configbk

# modify
if grep "\"$oldPort\"" $config &> /dev/null
then
    sed -i -e "s|\"$oldPort\"|\"$newPort\"|" $config
else
    echo "[INFO] oldPort not found, try to add a new Port_Password pair."
    sed -i -e "/port_password/a \\\t\"$oldPort\": \"$newPort\"," $config
fi

# diff and show modification
if diff $config $configbk &> /dev/null
then
    echo "[ERROR] Config not modified."
    rm $configbk
    exit 1
else
    echo "[INFO] Config file after modified:"
    cat $config
    echo "[INFO] end"
fi


read -p "[INFO] Restart shadowsocks? [y/n]" -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "[INFO] Modifying firewall..."
    firewall-cmd --remove-port=${oldPort}/tcp --permanent
    firewall-cmd --remove-port=${oldPort}/udp --permanent
    firewall-cmd --add-port=${newPort}/tcp --permanent
    firewall-cmd --add-port=${newPort}/udp --permanent
    firewall-cmd --reload
    echo "[INFO] Restarting shadowsocks..."
    systemctl restart shadowsocks
    systemctl status shadowsocks -l
    echo "[SUCCESS] Modified and backed up."
    exit 0
else
    cp $configbk $config
    rm $configbk
    echo "[ERROR] Config not modified."
    exit 0
fi
